### ISSUE TITLE
Language selection not clear and not in the help

### ISSUE THREAD

**Issue by ttohu** [Lathanda/Eos2#1]
The program seems to start up based on the windows default language.
Its not clear what parameter to use and how to force it into german or english at startup. 
Please amend documentation and help and publish here or on your website how to do this.

-Meanwhile realized from reverse engineering from source code, one has to start with eos.jar /d for German and eos.jar /e for English, otherwise the language is set by the Windows locale.

**Comment by Lathanda** [comment]
Your analyse is true. (I wonder why github doesn't send an email if a issue is opened?)
Supporting multiple Languages was more or less a prove of concept, hoping eos it would prove useful outside of germany. Using the system default language seems to be the way to go, as the target use is within schools and therefore one design target of the interface is to keep it as simple as possilble.
A feature like changing language is only interesting for few people.
